= Passwords
Ryan Schuetzler <rschuetzler@unomaha.edu>
v0.1, 2018-05-11
:icons: font
ifndef::bound[:imagesdir: images]
:xrefstyle: short
:date: 2018-05-11
:tags: security; passwords
:slug: passwords
:authors: Ryan Schuetzler
:status: draft
:summary: 

Your passwords are bad.
But you're not alone.
Almost everybody's passwords are bad cite:[BadPasswordsTroyHunt].
But don't feel too bad.
Your passwords are bad because everything you've been taught about passwords is probably wrong.

Let's fix that.

== What you're doing wrong
You've probably been making bad passwords for as long as you've been making passwords.
Let me guess what happens when you make a password:

*Step 1.* Use the same password you use for every other website. Something like `GoMavs123`. This is a "good" password because it's easy to remember. Plus, it has lowercase and uppercase letters, and even a number!

*Step 2.* The website tells you that you need a special character, so you add an exclamation point to the end: `GoMavs123!`.

*Step 3.* You're in.

Now, some people play this a little differently.
You might have 3 different passwords that you use depending on how "secure" you want to be on that site.
You might even have a password that changes slightly for each site you visit: `GoMavs123!`, `GoMavsFacebook123!`, `GoMavsTwitter123!`.
The fact is that most people simply can't remember enough passwords to have a unique one for every site you visit, so you take shortcuts.
That's completely understandable, but super risky.

Why is reusing passwords a bad idea?
Think about what happens when a website gets hacked (and we find out about it): they immediately send a notification to their users to change their passwords.
And they probably don't let users use the old password to log in, so that protects that site.
But what about all the other sites where you reused your password?
Do you go around to 20 different websites and update your password on all of them immediately?
Or instead do you just forget about it?

Unless you are extremely diligent about changing your password on every site with every hack, you are vulnerable to _credential stuffing_.


* Short passwords
* Common passwords
* Reusing passwords 

== Password managers

== Two-factor authentication
